language: python

python:
    - "2.7"

branches:
  only:
    - master

env:
    - TOXENV=py26
    - TOXENV=py27

before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/

install:
    - pip install tox --use-mirrors

script:
    - tox

after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls
